version: "3.9"

name: petclinic-tools

services:

  nexus:
    image: sonatype/nexus3:latest
    container_name: petclinic-nexus
    ports:
      - "8081:8081"   
      - "8082:8082"   
    volumes:
      - nexus_data:/nexus-data

 
  sonarqube:
    image: sonarqube:latest
    container_name: petclinic-sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

 
  prometheus:
    image: prom/prometheus:latest
    container_name: petclinic-prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:latest
    container_name: petclinic-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  nexus_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  prom_data:
  grafana_data:
